# Generated by Django 3.0.6 on 2020-08-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='lname',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='mnum',
            new_name='Mobile_number',
        ),
    ]
